# @package _group_
name: foldingnet

# FoldingNet Model Configuration
encoder_name: "pointnet"
encoder_args:
  feat_dims: 512

decoder_name: "folding"
decoder_args:
  grid_dims: [45, 45]
  grid_size: 2025
  feat_dims: 512
