# @package _group_
name: pqae

# Point-PQAE Model Configuration
min_crop_rate: 0.6
num_group: 64
group_size: 32
embed_dim: 384
trans_dim: 384
encoder_depth: 12
encoder_num_heads: 6
decoder_depth: 4
decoder_num_heads: 6
drop_path_rate: 0.1
