# configs/dataset/3dcell.yaml

name: "3072"
root: "/home/verve/Project/research/CellPoint/datasets/3dcell"
num_points: 3072
normalize: true
random_jitter: false
random_rotate: false
random_translate: false