# hyperparameters
batch_size: 8
epochs: 2000
lr: 0.001
weight_decay: 1e-6
min_lr: 1e-7

# other settings
num_workers: 4
save_interval: 25

# Visualization settings
visualize_every_n_epochs: 25
visualization_indices: [0, 1, 71, 72]

# Checkpoint settings
checkpoint_path: null
resume_training: false 