# hyperparameters
batch_size: 8
epochs: 300
warmup_epochs: 10
lr: 0.0005
weight_decay: 0.05
min_lr: 1e-6

# other settings
num_workers: 4
save_interval: 10

# Visualization settings
visualize_every_n_epochs: 25
visualization_indices: [65,888]

# Checkpoint settings
checkpoint_path: null
resume_training: false 