# configs/training/default.yaml

# hyperparameters
batch_size: 8
epochs: 20
lr: 0.0001
weight_decay: 1e-6
min_lr: 1e-6

# other settings
num_workers: 4
val_every_n_epochs: 10

# Visualization settings
visualize_every_n_epochs: 10
visualization_indices: [0, 1, 2]

# Checkpoint settings
checkpoint_path: null
resume_training: false 

# Weights & Biases (W&B) logging configuration
wandb:
  project: "CellPoint"
  log: true
  log_freq: 100
  mode: "offline"  # options: "online", "offline", "disabled"