# hyperparameters
batch_size: 8
epochs: 300
warmup_epochs: 10
lr: 0.0005
weight_decay: 0.05
min_lr: 1e-6

# other settings
seed: 42
num_workers: 4
save_interval: 10

# Checkpoint settings
checkpoint_path: null
resume_training: false

# data augmentation settings
augmentations:
  rotate: true
  scale_and_translate: false
  jitter: true
  
  scale_low: 0.8
  scale_high: 1.2
  translate_range: 0.2
  jitter_clip: 0.05
  jitter_sigma: 0.01