# configs/config.yaml

defaults:
  - dataset: 3dcell-2048
  - model: foldingnet
  - training: default
  - _self_

# global variables
project_name: "FoldingNet_3DCell"
seed: 42

hydra:
  job:
    chdir: true
  run:
    dir: outputs/${dataset.name}/${model.name}/k${model.k}_feat${model.feat_dims}_grid${model.grid_size}
  sweep:
    dir: multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: lr_${training.lr}_k_${model.k}